name: Deploy Angular app to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --base-href /

      - name: Build Docker image
        run: docker build -t codecoffee2024/portfolio-ui:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push codecoffee2024/portfolio-ui:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull codecoffee2024/portfolio-ui:latest
            if [ "$(docker ps -q -f name=portfolio-ui)" ]; then
              docker stop portfolio-ui
            fi
            if [ "$(docker ps -aq -f name=portfolio-ui)" ]; then
              docker rm portfolio-ui
            fi
            docker run -d -p 80:80 --name portfolio-ui codecoffee2024/portfolio-ui:latest
